PUT http://localhost:3000/api/rule


########

POST http://localhost:3000/api/rule
Content-Type: application/json

{
    "documents":
    [
        {
            "id": 1,
            "text": "You can not answer calls with the unit, never worked once!",
            "language": "en",
        }
    ]
}
